{% set name = "HyperGBM" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DataCanvasIO/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: dfdf7d31417eefcaed8d2517753f4523e0ed79451986ecdf56b60700f6909420

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - hypergbm = hypergbm.utils.tool:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - hypernets >=0.3.2, <0.4.0
    - numpy >=1.16.5
    - pandas >=0.25.3
    - scikit-learn >=0.22.1
    - imbalanced-learn >=0.7.0
    - lightgbm >=3.2.0
    - xgboost >=1.3.0
    - py-xgboost >=1.3.0
    - catboost >=0.26
    - fsspec >=0.8.0
    - tqdm
    - plotly
    - graphviz
    - python-graphviz
    - shap
    - matplotlib <3.6
    - pytest

test:
  imports:
    - hypergbm
  requires:
    - pip
  commands:
    - pip check  # [not win]
    - hypergbm --help  # [not win]
    - python -m hypergbm.utils.tool --help  # [win]

about:
  home: https://github.com/DataCanvasIO/HyperGBM
  license: Apache-2.0
  license_file: LICENSE
  summary: 'A full pipeline AutoML tool integrated various GBM models.'
  description: |
    HyperGBM is a full pipeline automated machine learning (AutoML) toolkit
    designed for tabular data. It covers the complete end-to-end ML processing stages,
    consisting of data cleaning, preprocessing, feature generation and selection,
    model selection and hyperparameter optimization.
  doc_url: https://hypergbm.readthedocs.io/
  dev_url: https://github.com/DataCanvasIO/HyperGBM

extra:
  recipe-maintainers:
    - lixfz
